spring:
  datasource:
    url: jdbc:postgresql://${env.ELEPHANT_SERVER}:5432/${env.ELEPHANT_USER}?socketTimeout=3
    username: ${env.ELEPHANT_USER}
    password: ${env.ELEPHANT_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

