spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-spring
    username: admin
    password: EcommErce.sql1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

