version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: ecommercepsql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce-spring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - ecommerce
 
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ecommerceadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgAdmin
    ports:
      - "80:80"
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - ecommerce
 
networks:
  ecommerce:
    driver: bridge

volumes:
  postgres_data:
  pg_data: